### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by qazip** [connorlanigan/norvos#15]
I'd very much like an alternative to the chrome-app that whispersystems calls "desktop client".

Is this project dead?

**Comment by connorlanigan** [comment]
I stopped working on this project after the official desktop client was released for some time, and currently I don't have the time to pick it up again as a developer, and there are no other developers working on it. However, that doesn't mean this project has to be dead: if you want to develop (or know people who would), your contribution would be very welcome!

The APIs should still be working, so there'd be no problem in using them.
If you have any questions or need some help, I'm always available. :)

**Comment by Ch3ck** [comment]
@partik1  I guess you want to bring back from the dead? ;-)
